### PR TITLE
few comments are added.

### PR DESCRIPTION
**Pull request by sarayusreeyadavpadala**
Hey geekcomputers! Let me know if any changes required.

### CODE REVIEW

**Review by NitkarshChourasia — APPROVED** [review]
Alright!

**Comment by sarayusreeyadavpadala** [comment]
Thanks NitkarshChourasia

**Comment by NitkarshChourasia** [comment]
Do check the last commit, a commit below yours and review my code too.

**Comment by sarayusreeyadavpadala** [comment]
For sure!

**Comment by NitkarshChourasia** [comment]
Thanks @sarayusreeyadavpadala

**Pull request merged**
