### PR TITLE
Reformat Code

### PR DESCRIPTION
**Pull request by JeromeK13**
Signed-off-by: Jérôme Krell <jerome.krell@bluewin.ch>

I thought it could be helpful to have consistent Code-Format overall examples.

Greets
Jérôme

### CODE REVIEW

**Comment by JeromeK13** [comment]
Hey @cclauss 
Thanks for the tip, see the PR-Fix here
https://github.com/geekcomputers/Python/pull/665

**Comment by cclauss** [comment]
Keep watching your Travis results.  https://travis-ci.com/JeromeK13/Python/builds

You should try to get those tests to be green ✅ .

If you got questions, I am happy to help.  Us Swiss coders need to stick together.

**Review by NitkarshChourasia — COMMENTED** [review]
Good stuff.

**Comment by mahnazghanbar197** [comment]
https://github.com/torvalds/linux.git

**Pull request merged**
