### PR TITLE
Calculator_with_simple_ui. Py

### PR DESCRIPTION
**Pull request by Adarshjaiss**
This is a how you can create a simple calculator using python with a decent ui.

### CODE REVIEW

**Review by slowy07 — COMMENTED** [review]
can you make to python file, because there's no extension on this file,
example for naming
``calculator_with_simple_ui.py``

thanks!!

**Comment by Adarshjaiss** [comment]
> can you make to python file, because there's no extension on this file,
> example for naming
> `calculator_with_simple_ui.py`
> 
> thanks!!

I have corrected that. Please review again and merge this pr. It's an humble request

**Comment by Adarshjaiss** [comment]
> can you make to python file, because there's no extension on this file,
> example for naming
> `calculator_with_simple_ui.py`
> 
> thanks!!

Hello sir, 
It's an humble request from my side,
please review this pr and merge it. I have made all those changes which you have suggested

**Comment by Adarshjaiss** [comment]
@slowy07 
Hello sir,
It's an humble request from my side,
please review this pr and merge it. I have made all those changes which you have suggested

**Pull request merged**
