### PR TITLE
start  local server

### PR DESCRIPTION
**Pull request by ashwini0529**
This will start a local server on the mentioned port.
This is a good utility tool.

### CODE REVIEW

**Comment by ashwini0529** [comment]
Don't we need this?

**Comment by ashwini0529** [comment]
@geekcomputers, please reply.

**Comment by geekcomputers** [comment]
start local server? What do you mean

**Comment by ashwini0529** [comment]
If you'll run this script, this will start a HTTP Client server on your localhost.
Run this script and open up your browser, and goto `localhost:8000` , you can see the directory listing.
This is very useful for understanding local servers.

**Comment by geekcomputers** [comment]
Yes it a very handy fetaure, glad you like it :-)

**Comment by ashwini0529** [comment]
I guess, that should be merged if there's no harm in doing that? ;)

**Pull request merged**
