### PR TITLE
A new program: is_number.py, to check for numbers of any kind.

### PR DESCRIPTION
**Pull request by NitkarshChourasia**
Adding a program named is_number.py.
Which checks whether a input object is number of any form or not.
It has OOP, KISS, DRY and Docstring and industry best coding practices, implemented.

### CODE REVIEW

**Review by NitkarshChourasia — COMMENTED** [review]
Good program.

**Comment by NitkarshChourasia** [comment]
@OfficialAhmed @sarayusreeyadavpadala

**Review by NitkarshChourasia — COMMENTED** [review]
Successful.

**Review by OfficialAhmed — APPROVED** [review]

**Comment by sarayusreeyadavpadala** [comment]
> Adding a program named is_number.py. Which checks whether a input object is number of any form or not. It has OOP, KISS, DRY and Docstring and industry best coding practices, implemented.

Nice one @NitkarshChourasia

**Comment by NitkarshChourasia** [comment]
> > Adding a program named is_number.py. Which checks whether a input object is number of any form or not. It has OOP, KISS, DRY and Docstring and industry best coding practices, implemented.
> 
> Nice one @NitkarshChourasia

Yes I know.

**Comment by sarayusreeyadavpadala** [comment]
@NitkarshChourasia congratulations!

**Pull request merged**
