### PR TITLE
Added Industrial_developed_hangman

### PR DESCRIPTION
**Pull request by danila12315454**
Added example of Industrial developed game Hangman

### CODE REVIEW

**Review by NitkarshChourasia — CHANGES_REQUESTED** [review]
A screenshot would be better if it is embedded in to README.md file.

**Comment by danila12315454** [comment]
screenshot of programm working?

**Comment by NitkarshChourasia** [comment]
> screenshot of programm working?

Yes, would be better. This is all perfect. Just for those who wanna just scroll through the repo so that they can know better, what is this.

**Comment by danila12315454** [comment]
> A screenshot would be better if it is embedded in to README.md file.

done

**Comment by danila12315454** [comment]
I also have a question about adding github workflow in file. Will it work correctly? I am talking about yml file

**Comment by NitkarshChourasia** [comment]
@OfficialAhmed Please, check this out.

**Review by OfficialAhmed — APPROVED** [review]
All good however
- **_Scraping a word_**: I dont recommend scraping a web page for a word. I rather use an api to fetch words which is much safer and better approach to this problem. Please consider the policy and the rules of the website that is being scraped it might be illegal to do so or they dont allow that. 

- **_Hard coded_**: It would be better to first check if the HTML element that contains the word exist before scraping because this could be an issue the future if the website gets changed or updated

**Pull request merged**
