### PR TITLE
Wordle console game

### PR DESCRIPTION
**Pull request by KevinGiesberts**
A console game wordle clone. With comments that explain everything that the code does

### CODE REVIEW

**Review by DontEatThemCookies — APPROVED** [review]
Neat idea. Although I do see a few things that can use improvement, it looks good in general. I might work on improving this if this gets merged.

**Comment by KevinGiesberts** [comment]
@DontEatThemCookies What could I improve upon?

**Comment by KevinGiesberts** [comment]
@DontEatThemCookies I just found a bug in the checking algorithm and I am currently working on a fix.

**Comment by DontEatThemCookies** [comment]
> @DontEatThemCookies What could I improve upon?

Well for one, I think there's a bit too many comments. Perhaps try removing comments from parts that you think is obvious enough that doesn't warrant a dedicated comment. Beside that, there's other things that can be optimized, for instance the dictionary definition, you can use the `with` statement (context manager) so that it looks cleaner and doesn't require a separate `close()` instruction:
```py
# Read the dictionary and make a list out of all the words
with open("5 letter word dictionary.txt", 'r') as dictionary:
    dictionary = dictionary.read().split('\n')
```

**Pull request merged**
