### PR TITLE
modified code for readability and security

### PR DESCRIPTION
**Pull request by rohitbabugaddeti**
since readability is one of the most important things when you code, I've modified the code so that others can read and understand it easily :)

### CODE REVIEW

**Comment by MockArch** [comment]
can you rename 
`modified code for readability and security`  to `modified_code_for_readability_and_security`  
Best Practice

**Comment by rohitbabugaddeti** [comment]
> can you rename
> `modified code for readability and security` to `modified_code_for_readability_and_security`
> Best Practice

I understand your concern @MockArch . But it is a commit message and I don't think that what you are asking is possible (I only know that branch name shouldn't have white spaces). If possible, please help me to do it. I'm a newbie :).

Thanks in advance

**Comment by MockArch** [comment]
i m extremely, i have found a lot of white spaced file name , that is really annoyed me. My bad! i just got confused with it. anyways thanks ! :) :+1:

**Comment by geekcomputers** [comment]
Thank you for you contribution to the repo and the community

**Pull request merged**
