### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sanikaahadap**
Fixed typo

### CODE REVIEW

**Review by NitkarshChourasia — APPROVED** [review]
Good catch.

**Comment by sanikaahadap** [comment]
Can you merge the pull request, sir?

**Comment by NitkarshChourasia** [comment]
Will be done.
Hello,
My name is Nitkarsh Chourasia.
I am a professional Python Developer from India, Maharashtra, South Mumbai
Let's connect:
GitHub: https://github.com/NitkarshChourasia

LinkedIn : https://www.linkedin.com/in/nitkarshchourasia

**Comment by NitkarshChourasia** [comment]
> Can you merge the pull request, sir?

https://chat.whatsapp.com/ICJdMvoSrFVG7StsCEkQhs

This is a community where we do and solve and support and encourage competitive programming (DSA mostly people know by).

Do mind connecting.

Best regards,

Nitkarsh Chourasia

**Comment by NitkarshChourasia** [comment]
> Can you merge the pull request, sir?

Done.

**Comment by NitkarshChourasia** [comment]
@sanikaahadap

**Pull request merged**
