### PR TITLE
Update tictactoe.py

### PR DESCRIPTION
**Pull request by shritej1808**
pushing changes

### CODE REVIEW

**Review by NitkarshChourasia — CHANGES_REQUESTED** [review]
Irrelevant Change.
Will not be counted as Refactoring.

**Comment by NitkarshChourasia** [comment]
@geekcomputers **DO NOT MERGE IT.**

**Review by ultrasage-danz — COMMENTED** [review]
ok

**Review by ultrasage-danz — APPROVED** [review]
clean

**Pull request closed without merging**
