### PR TITLE
Made code compatible with Python 2 & 3

### LINKED ISSUE #312: TicTacToe.py inputs aren't working
The player inputs for function inputPlayerLetter(), playAgain(), and getPlayerMove() aren't being recognized and working.  I changed it from input to raw_input and the game is working as expected.  I know the raw_input should be used for strings which makes since why input didn't work for inputPlayerLetter() and getPlayerMove(), but it doesn't make sense why input doesn't work getPlayerMove().

### PR DESCRIPTION
**Pull request by Anubhav-Bhargava**
**Problem**
The code was throwing error while running with Python 2

**Solution**
Updated the code to check for the python version and take the input accordingly.

Fix #312

### CODE REVIEW

**Comment by Scotttresor** [comment]
Can i help

**Comment by Anubhav-Bhargava** [comment]
@Scotttresor Ya sure :)

**Comment by Scotttresor** [comment]
Ok so good but what can i do???

**Comment by geekcomputers** [comment]
Thank you for you contribution to the repo and the community

**Pull request merged**
