### PR TITLE
Fixed Typos

### PR DESCRIPTION
**Pull request by SkJishan04**

### CODE REVIEW

**Comment by NitkarshChourasia** [comment]
@PBJI Do you agree with it?

**Review by PBJI — APPROVED** [review]

**Comment by NitkarshChourasia** [comment]
@complex programs when implemented with dot notation of class.methods is a good way and practice in coding.
Here, @SkJishan04 removes it and then commits it as a feature improvement. Which wasn't anything.

@PBJI Thanks for your time and review.
- @NitkarshChourasia

**Comment by Depu1322** [comment]
Hlo bai mna thodi se hacking sikni to bai banka sika de🙄☹️

**Comment by NitkarshChourasia** [comment]
Purshottam ji

**Pull request closed without merging**
