### PR TITLE
JARVIS.py: Used dict.get() to simplify and accelerate

### PR DESCRIPTION
**Pull request by cclauss**
JARVIS.py: Used dict.get() to simplify and accelerate get_app()

Easily add new cmds or modify the function to read in allowed commands from a json or similar configuration file.

@Shokr Your review please.

### CODE REVIEW

**Comment by cclauss** [comment]
@Shokr Can you please review the code by clicking `Files changed` above then `Review changes` then `Approve` then `Submit review`?

**Comment by Shokr** [comment]
Good job everybody.

**Comment by Shokr** [comment]
Done

**Comment by Shokr** [comment]
Dear @cclauss ,

I sent an invitation to you to the main project repo, to be free to make more of what you want.

Thanks

**Comment by kuldeep60** [comment]
Good

**Pull request closed without merging**
